export const AUTHENTICATED = 'AUTHENTICATED';
export const MODAL_TYPE = 'MODAL_TYPE';
export const SIGN_IN_REQUESTED = 'SIGN_IN_REQUESTED';
export const SIGN_IN_RECEIVED = 'SIGN_IN_RECEIVED';
export const SIGN_IN_REJECTED = 'SIGN_IN_REJECTED';
