// Designation
export const DESIGNATION_UPDATE = 'DESIGNATION_UPDATE'
export const DESIGNATION_EDIT_MODE = 'DESIGNATION_EDIT_MODE'

// Description
export const CONTACT_DESCRIPTION_UPDATE = 'CONTACT_DESCRIPTION_UPDATE'
export const CONTACT_DESCRIPTION_EDIT_MODE = 'CONTACT_DESCRIPTION_EDIT_MODE'

// Phone
export const PHONE_UPDATE = 'PHONE_UPDATE'
export const PHONE_EDIT_MODE = 'PHONE_EDIT_MODE'

// Email
export const SET_EMAIL = 'SET_EMAIL'

// Location
export const LOCATION_UPDATE = 'LOCATION_UPDATE'
export const LOCATION_EDIT_MODE = 'LOCATION_EDIT_MODE'
