export const SET_PARENT_MESSAGES = 'SET_PARENT_MESSAGES'
export const SET_PRIVATE_MESSAGES = 'SET_PRIVATE_MESSAGES'
export const SET_SEND_MESSAGE_DATA = 'SET_SEND_MESSAGE_DATA'
export const SET_TOTAL_NOTIFICATION_COUNT = 'SET_TOTAL_NOTIFICATION_COUNT'
