export const REMOVE_PORTFOLIO = 'REMOVE_PORTFOLIO'
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES'
export const UPDATE_TITLE = 'UPDATE_TITLE'
export const UPDATE_DESCRIPTION = 'UPDATE_DESCRIPTION'
