const FontAwesomeIcons = {
    "facebook": "fab fa-facebook-f",
    "github": "fab fa-github-alt",
    "linkedin": "fab fa-linkedin-in",
    "bars": "fas fa-bars",
    "bookOpen": "fas fa-book-open",
    "tv": "fas fa-tv",
    "tools": "fas fa-tools",
    "cogs": "fas fa-cogs",
    "slack": "fab fa-slack",
    "arrowRight": "fas fa-arrow-right",
    "arrowUp": "fas fa-arrow-up",
    "heart": "far fa-heart",
    "clock": "far fa-clock",
    "thumbsUp": "far fa-thumbs-up",
    "angleRight": "fas fa-angle-right",
    "pencil": "fa-solid fa-pencil",
    "signIn": "fa-solid fa-right-to-bracket",
    "trash": "fa-solid fa-trash",
    "darkMode": "fa-solid fa-moon",
    "plus": "fa-solid fa-plus",
    "chevronLeft": "fa-solid fa-chevron-left",
    "camera": "fa-solid fa-camera",
    "selected": "fa-solid fa-circle-check",
    "users": "fa-solid fa-user-group",
    "briefcase": "fa-solid fa-briefcase",
    "location": "fa-solid fa-location-dot",
    "dollar": 'fa-solid fa-money-check-dollar'
}

export default FontAwesomeIcons;
